# Site settings
title: "Letmeunsubscribe"
description: "keeping vigilant on shady cancellation methods out there."
baseurl: "/letmeunsubscribe"
url: "https://octopodsio.github.io/letmeunsubscribe/"
author: "Tarek Khalil"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
